#ifndef __OFFSETS_RT_H
#define __OFFSETS_RT_H

void offsets_init (unsigned dcb_version, int sglobal, int slocal);

extern int MOUSEX, MOUSEY, MOUSEGRAPH, MOUSEFILE, MOUSEZ, MOUSEANGLE, MOUSESIZE,
    MOUSEFLAGS, MOUSEREGION, MOUSELEFT, MOUSEMIDDLE, MOUSERIGHT,
    MOUSEWHEELUP, MOUSEWHEELDOWN, SCROLLS,
    JOYLEFT, JOYRIGHT, JOYUP, JOYDOWN, JOYBUTTON1, JOYBUTTON2, JOYBUTTON3, JOYBUTTON4,
    SETUPCARD, SETUPPORT, SETUPIRQ, SETUPDMA, SETUPDMA2, SETUPMASTER, SETUPSOUNDFX, SETUPCDAUDIO,
    TIMER, TEXTZ, FADING, SHIFTSTATUS, ASCII, SCANCODE, JOYFILTER, JOYSTATUS,
    RESTORETYPE, DUMPTYPE, MAXPROCESSTIME, M7STRUCTS,
    FPS, TEXT_FLAGS, PANSEP, REVERB, VOLUME, SOUND_FREQ, SOUND_MODE, GRAPH_MODE,
    SCALE_MODE, ARGC, ARGV_TABLE, SPEED_GAUGE, FRAME_TIME, REGEX_REG, ALPHA_STEPS,
    FILE_PATH, FILE_NAME, FILE_DIRECTORY, FILE_HIDDEN, FILE_READONLY, FILE_SIZE,
    FILE_CREATED, FILE_MODIFIED, FULL_SCREEN,
    EXIT_STATUS, WINDOW_STATUS, FOCUS_STATUS, MOUSE_STATUS,
    CD_TRACK, CD_FRAME, CD_TRACKS, CD_MINUTE, CD_SECOND, CD_SUBFRAME,
    CD_MINUTES, CD_SECONDS, CD_FRAMES, CD_TRACKINFO, FXI_OS, SOUND_CHANNELS;

extern int PROCESS_ID, ID_SCAN, PROCESS_TYPE, TYPE_SCAN, STATUS, CHANGED,
    XGRAPH_FLAGS, SAVED_STATUS, PREV_Z, DISTANCE_1, DISTANCE_2, FRAME_PERCENT,
    BOX_X0, BOX_Y0, BOX_X1, BOX_Y1, FATHER, SON, SMALLBRO, BIGBRO, PRIORITY,
    CTYPE, CFLAGS, COORDX, COORDY, COORDZ, GRAPHID, PALETTEID, FLAGS, GRAPHSIZE,
    ANGLE, REGIONID, FILEID, XGRAPH, HEIGHT, RESOLUTION, ALPHA, GRAPHSIZEX, GRAPHSIZEY,
    BLENDOP, SAVED_X, SAVED_Y, SAVED_GRAPH, SAVED_PALETTE, SAVED_ANGLE, SAVED_ALPHA,
    SAVED_BLENDOP, SAVED_SIZE, SAVED_SIZEX, SAVED_SIZEY, SAVED_FLAGS, SAVED_FILE,
    SAVED_XGRAPH, SAVED_PRIORITY;

#endif
